default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE", 5) %>
  timeout: 5000
  database: blogbowl

development:
  <<: *default
  username: development
  password: development
  host: localhost
  port: 5435

test:
  <<: *default
  database: test
  username: test
  password: test
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5434) %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
