// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import MembersController from './members_controller';
import LinksController from './links_controller';
import AuthorLinksController from './author_links_controller';
import DomainController from './domain_controller';
import ResizableIframeController from './resizable_iframe_controller';
import NewsletterDomainController from './newsletter_domain_controller';
import ImageInputController from './image_input_controller';
import DismissibleController from './dismissible_controller';

application.register('members', MembersController);
application.register('links', LinksController);
application.register('author_links', AuthorLinksController);
application.register('domain', DomainController);
application.register('newsletter_domain', NewsletterDomainController);
application.register('resizable_iframe', ResizableIframeController);
application.register('image_input', ImageInputController);
application.register('dismissible', DismissibleController);
